# 인공지능 수학 - 선형대수 (NumPy 실습)
## 행렬과 벡터의 코딩 및 연산

In [1]:
import numpy as np

In [19]:
# 행렬 코딩
A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])

print(A)
print(np.shape(A))
print(A.T)

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)
[[ 3  1  1]
 [ 1 -2  1]
 [ 1 -1  1]]


In [12]:
# 벡터 코딩
b = np.array([4, 1, 2])

print(b)
print(np.shape(b))

[4 1 2]
(3,)


In [16]:
# 역행렬 구하기
A_inv = np.linalg.inv(A)

print(A_inv)
print(np.shape(A_inv))


[[-0.5  1.   1.5]
 [-1.   1.   2. ]
 [ 1.5 -2.  -2.5]]
(3, 3)


In [5]:
# 역행렬을 이용한 선형시스템 Ax=b의 해 구하기
# x = np.matmul(A_inv, b)
x = A_inv @ b

print(x)
print(np.shape(x))

[ 1. -1.  2.]
(3,)


In [20]:
## 결과 검증
# bb = np.matmul(A, x)
bb = A @ x 

print(np.shape(bb))
print(bb)

if np.linalg.norm(b - bb) < 1e-3:
  
  print("Ok")
else:
  print("something wrong")

(3,)
[4. 1. 2.]
0.0
Ok


- 선형 방정식과 비선형 방정식

    - $\sin{x}+2$   -> 비선형방정식
    - $2x + y = 3$  -> 선형방정식
    - $xy + z = 3$  -> 비선형방정식

- Linear System의 해 구하기

    -  예시 1. $E_1$, $E_2$, $E_3$로 구성된 선형시스템

- 가우스 소거법으로 해 구하기 

$
\begin{cases}
3x + y -z = 4\\
x - 2y -z = 1\\
x + y + z = 2\\
\end{cases} \to
\begin{cases}\begin{aligned}
3x + y -z &= 4\\
2x - y    &= 3\\
x + y + z &= 2\\
\end{aligned}\end{cases} 
$

    

- 선형시스템의 대수적 표현으로 해 구하기 : $Ax = b$ -> $x = A^{-1}b$
        
    $
    \begin{pmatrix}3&1&-1 \\1&-2&-1 \\ 1&1&1 \end{pmatrix} \begin{pmatrix}x \\y \\ z \end{pmatrix} = \begin{pmatrix} 4 \\1 \\2 \end{pmatrix} \to
    \begin{pmatrix}3&1&-1 \\1&-2&-1 \\ 1&1&1 \end{pmatrix} \begin{pmatrix}x \\y \\ z \end{pmatrix} = \begin{pmatrix} 4 \\1 \\2 \end{pmatrix}
    $

In [17]:
import numpy 

A = np.array([[3,1,1],[1,-2,-1],[1,1,1]])
b = np.array([4,1,2])

A_inverse = np.linalg.inv(A)
print(A_inverse)

[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]


In [18]:
x = A_inverse @ b

print(x)

[ 1. -1.  2.]


$m\times n$선형시스템의 $Ax = b$표현을 정리하면 다음과 같다.

- 식은 행, 행은 식이다 (필요충분조건)
- $m$은 선형방정식의 개수
- $n$은 미지수의 개수
- A는 $m\times n$행렬
- $x$는 $n$벡터
- $b$는 $m$벡터

---

## 가우스 소거법 

- 선형 시스템의 해 

선형시스템 $ax=b$에 대해

- a = 0이면 특이하다.(a의 행렬식이 0인 경우)
- a의 역행렬이 존재하지 않는 경우, a가 `singular(특이)하다` 
- 해가 존재하면, 선형시스템이 `consistent`
- 존재하지 않으면, 선형시스템이 `inconsistent`

1. 해가 하나인 경우 `consistent`
2. 해가 없는 경우    `inconsistent`
3. 해가 여러개인 경우 `consistent`

---


#### Forward elimination(전방소거법)
- 선형시스템을 아래로 갈수록 더 간단한 형태로 정리함 : A를 `상삼각행렬`로 만듦

$
    \begin{pmatrix}3&1&-1 \\1&-2&-1 \\ 1&1&1 \end{pmatrix} \begin{pmatrix}x \\y \\ z \end{pmatrix} = \begin{pmatrix} 4 \\1 \\2 \end{pmatrix} \to
    \begin{pmatrix}a_1&a_2&a_3 \\0&a_4&a_5 \\ 0&0&a_6 \end{pmatrix} \begin{pmatrix}x \\y \\ z \end{pmatrix} = \begin{pmatrix} b_1 \\b_2 \\b_3 \end{pmatrix}
$

#### back-substitution(후방대입법)
- 아래부터 위로 미지수를 실제값으로 대체

$
\begin{pmatrix}a_1&a_2&a_3 \\0&a_4&a_5 \\ 0&0&a_6 \end{pmatrix} \begin{pmatrix}x \\y \\ z \end{pmatrix} = \begin{pmatrix} b_1 \\b_2 \\b_3 \end{pmatrix}
$ 형태에서 $z \to x$방향으로 해를 구해나갑니다.

---

- 소거법에서의 기본 행연산

    - 치환 : i번째 행을 m배하여 j행에 더함
    
     $r_j \larr r_j + m\times r_i$

    - 교환 : i행과 j행을 바꿈
    - 스케일링 : 해당 행을 k배

---


#### forward elimination의 가치
- 주어진 선형시스템을 해를 구하기 쉬운 형태
- 선형시스템의 **rank**를 알 수 있다.
- 선형시스템에 해가 존재하는지 ( consistent / inconsistent ) 여부를 알 수 있다.
---

rank : 독립인 행의 개수 (물론 열로 봐도 가능)

`A가 독립이면 해가 반드시 존재한다.`