# 인공지능 수학 - 선형대수 (NumPy 실습)

- 행렬 분해의 의미

    ex. 인수분해
    - `LU분해`
    - `QR분해` 
    - `특이값 분해`(SVD : Singular Value Decomposition)
    
- `QR분해`, `특이값 분해` : 직교분할
- LU분해 : 가우스 소거법, 행렬의 형태로.
---

## $A = LU$
- $L$: 상삼각행렬
- $U$: 하삼각행렬

`즉 특정행렬 $A$를 상삼각행렬과 하삼각행렬로 나눔`
---

### LU분해의 장점 
$Ax = b \to (LU)x=b \to L(Ux)=b \to Ly=b (\because Ux=y)$

- 전방대치법(Forward-substitution) 활용
$
\begin{pmatrix}l_1 & 0 & 0 \\l_2 & l_3 & 0 \\ l_4 & l_5 &l_6 \end{pmatrix} \begin{pmatrix}y_1 \\ y_2 \\ y_3 \end{pmatrix} = \begin{pmatrix} b_1 \\b_2 \\b_3 \end{pmatrix}
$

여기서 구한 $y$로 $Ux = y$에 대입하여 $x$를 구함

- 후방대치법(Backl-substitution) 활용
$
\begin{pmatrix}u_1&u_2&u_3 \\0&u_4&u_5 \\ 0&0&u_6 \end{pmatrix} \begin{pmatrix}x \\y \\ z \end{pmatrix} = \begin{pmatrix} b_1 \\b_2 \\b_3 \end{pmatrix}
$
---

- $L$ : 행렬 `A`를 전방소거하는데 쓰인 replacement, scaling에 대한 행연산을 기록해둔 행렬
- $U$ : 행렬 `A`를 전방소거 후 남은 상삼각행렬
- $P$ : 행렬 `A`를 전방소거하는데 쓰인 행교환(interchange)에 대한 행연산을 기록해둔 행렬

### LU 분해의 활용
- 수치적 안정성 : $A^{-1}$를 활용할 때보다, $PLU$분해를 이용하는 것이 더 안정적이다. 역행렬 자체가 수치적으로 불안정할 때가 많음.
- b가 자주 업데이트 됨 : $A \to PLU$시 $b$가 자주 업데이트 된다고 하더라도 선형시스템의 해를 실시간으로 구할 수 있음.


## LU 분해 (가우스 소거법), 행렬의 rank

In [2]:
%pip install scipy

  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/63/b9/0344b60e7c577eb637785841222fde8ef7928ec4797be1a34ca39bfe31dc/scipy-1.11.2-cp310-cp310-macosx_12_0_arm64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.3/100.3 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.6/29.6 MB 34.6 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
import scipy        
import scipy.linalg   # LU 분해를 사용하기 위한 import 

In [4]:
# 행렬 A, 벡터 b 코딩
A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])
b = np.array([4, 1, 2])

print("A:", A)
print(np.shape(A))

print("b:", b)
print(np.shape(b))

A: [[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)
b: [4 1 2]
(3,)


LU 분해 결과 확인하기

In [5]:
# LU 분해의 결과를 각각 행렬로서 확인하기
P, L, U = scipy.linalg.lu(A)

print("P:", P)
print("L:", L)
print("U:", U)

AA = P @ L @ U
print("AA:", AA)

P: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L: [[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.33333333 -0.28571429  1.        ]]
U: [[ 3.          1.          1.        ]
 [ 0.         -2.33333333 -1.33333333]
 [ 0.          0.          0.28571429]]
AA: [[ 3.  1.  1.]
 [ 1. -2. -1.]
 [ 1.  1.  1.]]


LU 분해를 이용한 선형시스템 Ax = b 풀기


In [10]:
# LU 분해
# U의 상삼각부분과 L의 하삼각부분으로 이뤄짐. L의 대각 원소들은 포함하지 않음.
# piv : i번째 행이 piv[i]로 교체됨.

lu, piv = scipy.linalg.lu_factor(A)

# (LU)x = b의 해를 구함
x = scipy.linalg.lu_solve((lu, piv), b)
# print(scipy.linalg.lu_solve(A, b))
print(lu,piv)
print("x:", x)
print(np.shape(x))

bb = A@x
print("bb:", bb)


[[ 3.          1.          1.        ]
 [ 0.33333333 -2.33333333 -1.33333333]
 [ 0.33333333 -0.28571429  0.28571429]] [0 1 2]
x: [ 1. -1.  2.]
(3,)
bb: [4. 1. 2.]


## 행렬의 rank 계산하기

'rank = 2'인 2x2 행렬 A


In [ ]:
A = np.array([[1, 3], [-2, 1]])
print("A:", A)

A: [[ 1  3]
 [-2  1]]


`matrix_rand()`

In [ ]:
print("rank:", np.linalg.matrix_rank(A))
A_inv = np.linalg.inv(A)  

print(A_inv)

rank: 2
[[ 0.14285714 -0.42857143]
 [ 0.28571429  0.14285714]]


'rank = 1'인 2x2 행렬 A

In [ ]:
A = np.array([[1, 3], [2, 6]])

print("A:", A)

A: [[1 3]
 [2 6]]


In [11]:
print("rank:", np.linalg.matrix_rank(A))
A_inv = np.linalg.inv(A)  

rank: 3


In [12]:
# LU 분해의 결과를 각각 행렬로서 확인하기
P, L, U = scipy.linalg.lu(A)

print("P:", P)
print("L:", L)
print("U:", U)

AA = P @ L @ U
print("AA:", AA)

P: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L: [[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.33333333 -0.28571429  1.        ]]
U: [[ 3.          1.          1.        ]
 [ 0.         -2.33333333 -1.33333333]
 [ 0.          0.          0.28571429]]
AA: [[ 3.  1.  1.]
 [ 1. -2. -1.]
 [ 1.  1.  1.]]


In [14]:
b = np.array([2, 4,1])
# LU 분해
lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print("x:", x)
print(np.shape(x))

x: [ 0.5 -4.   4.5]
(3,)


# 좌표계 변환

#### $Ax = b$ 다시보기
$Ax = (I)b$   

- $A$ : 좌표계
- $x$ : 좌표값
- $I$ : 표준 좌표계
- $b$ : 좌표값
---

- 벡터의 수학적 표현 : **좌표계를 도입**해서 시작점을 원점, 끝점의 위치를 벡터의 수학적 표현으로 정의했음.


- 벡터의 좌표계로의 해석

$
v = \begin{pmatrix} a \\ b \end{pmatrix}
= \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} \begin{pmatrix} a \\ b \end{pmatrix}
= a\begin{pmatrix} 1 \\ 0 \end{pmatrix} + b \begin{pmatrix} 0 \\ 1 \end{pmatrix}
$

- $a\begin{pmatrix} 1 \\ 0 \end{pmatrix}$ :  $x$축으로 내린 수선의 발. $x$축단위로 a번 전진

- $b\begin{pmatrix} 0 \\ 1 \end{pmatrix}$ :  $y$축으로 내린 수선의 발. $y$축단위로 b번 전진
---

$4v_1 + 3v_2 = v$
- $
\begin{aligned}
\begin{pmatrix} v_1 & v_2 \end{pmatrix} \begin{pmatrix} 4 \\ 3 \end{pmatrix} &= v \\
&= \begin{pmatrix} e_1 & e_2 \end{pmatrix} \begin{pmatrix} a \\ b \end{pmatrix}
\end{aligned}
$
처럼 볼 수 있다.

`즉, 하나의 벡터에 대해` $e_1$`과` $e_2$`를 기저로 가지는 표준좌표계로 해석하여 좌표값`$(a,b)$`으로도 표현할 수 있고, `$v_1$`과` $v_2$`를 기저로 가지는 좌표계로 해석하여 좌표값` $(4,3)$`으로도 표현할 수 있다.`

---

#### $Ax = b$ 좌표계 변환으로 해석하기
$Ax = (I)b$ : $b$를 기준으로 좌표계 해석

Ex.
$
\begin{pmatrix}1 & -1 \\ 2 & 2 \end{pmatrix} \begin{pmatrix} 2  \\ 1 \end{pmatrix} = \begin{pmatrix}1 \\ 6\end{pmatrix} 
$

- 어떤 벡터에 대해, 표준좌표계 기준 좌표값은 $\begin{pmatrix}1 \\ 6\end{pmatrix}$이다.
- $\begin{pmatrix}1 \\ 2 \end{pmatrix}$와 $\begin{pmatrix}-1 \\ 2 \end{pmatrix}$를 기저로 가지는 좌표계에서 이 벡터에 대한 좌표값이 $\begin{pmatrix} 2  \\ 1 \end{pmatrix}$이다.

#### 역향렬을 이용해 선형시스템의 해를 구할 때 좌표계 변환으로 바라보기
$x = A^{-1}b \to (I)x = A^{-1}b$  : $x$가 기준이 되어 동일하게 해석.

이 때, $A^{-1}$가 **좌표계**가 되어 두 열백터를 기저로 좌표계를 나타내게 된다.

---

#### 정리
행렬은 **좌표계**이며, 벡터는 **좌표값**이다.
임의의 벡터 $v$는 다양한 좌표계로 해석할 수 있다. 

$
\begin{aligned}
v &= A \begin{bmatrix}v\end{bmatrix}_A \\
&= B \begin{bmatrix}v\end{bmatrix}_B
\end{aligned}
$

위 식에서, 하나의 벡터 $v$에 대해 좌표계 $A$를 기준으로 표현된 좌푯값 $v_A$와 좌표계 $B$를 기준으로 표현된 좌푯값 $v_B$를 알 수 있다.

여기서, 좌표계 $A$에서 표현된 $v$인 $v_A$를 표준좌표계 위에 올려놓으면, $A^{-1}B$를 좌표계로 삼은 $v_B$좌표값이 나오고($\because \begin{bmatrix}v\end{bmatrix}_A = A^{-1}B\begin{bmatrix}v\end{bmatrix}_B$), $\\$
반대로 $v_B$를 표준좌표계 위에 올려놓으면, $B^{-1}A$를 좌표계로 삼은 $v_A$좌표값이 나온다.($\because \begin{bmatrix}v\end{bmatrix}_B = B^{-1}A\begin{bmatrix}v\end{bmatrix}_A$

---

#### 예제 1
어떤 벡터 $v$가 표준좌표계에서 $(2,1,3)$으로 표현된다.
벡터 $(1,3,1)$과 $(1,-2,2)$를 기저벡터로 가지는 새로운 좌표계를 도입할 때, 벡터 $v$는 어떤 좌표값을 가지는가?

$
\begin{pmatrix} 1 & 1 \\ 3 & -2 \\ 1 & 2 
\end{pmatrix}\begin{pmatrix} x_1 \\ x_2
\end{pmatrix} = \begin{pmatrix} 2 \\ 1 \\ 3
\end{pmatrix}
$의 해를 구하는 문제.

$
\therefore\begin{pmatrix} x_1 \\ x_2
\end{pmatrix} = \begin{pmatrix} 1 \\ 1
\end{pmatrix}
$

3차원 벡터 $\begin{pmatrix} 2 \\ 1 \\ 3
    \end{pmatrix}$를 두 기저벡터로 표현(평면위에 있다고 봄)하여, $(1,1)$로 해석함.